### ISSUE TITLE
Create Github Actions pipeline

### ISSUE THREAD

**Issue by sannawiklund** [sannawiklund/HealthCareAB#41]
- [x] Create folder structure > .github > workflows 
- [x] Create YAML workflow-file > ci.yaml

```
name: Github Actions - .NET Build and Test

on:
  push:
    branches: [develop]
    paths:
      - "**/*.cs"
      - "**/*.csproj"
      - "**/*.sln"
  pull_request:
    branches: [develop]
    paths:
      - "**/*.cs"
      - "**/*.csproj"
      - "**/*.sln"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Steg 1: Checka ut repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Steg 2: Ställa in .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0" # Ändra versionen om ditt projekt använder en annan .NET-version

      # Steg 3: Återställ beroenden
      - name: Restore dependencies
        run: dotnet restore

      # Steg 4: Bygga projektet
      - name: Build project
        run: dotnet build --configuration Release

      # Steg 5: Köra tester
      - name: Run tests
        run: dotnet test --no-build --configuration Release
```
 
- [x] Push YAML-file to repo > 
`git add .github/workflows/ci.yml`
`git commit -m "Add CI workflow"`
`git push origin main`
- [x] Test workflow in GitHub > Navigate to Actions
- [ ] Implement xUnit-tests #42
