### ISSUE TITLE
Update YAML-file for tests

### ISSUE THREAD

**Issue by sannawiklund** [sannawiklund/HealthCareAB#78]
Lägg till att alla förändringar som sker i projektmappen xUnitTests i vår solution triggar flödet, istället för endast en testbranch som det var tidigare

```
name: GitHub Actions CI

on:
  push:
    branches: [main]
    paths:
      - "xUnitTests/**/*" # Begränsar till projektmappen xUnitTests
  pull_request:
    branches: [develop]
    paths:
      - "xUnitTests/**/*" # Begränsar till projektmappen xUnitTests

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Run tests with coverage
        run: |
          dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage" \
          --logger "trx;LogFileName=test-results.trx"

      - name: Publish test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: "**/TestResults/*.trx"

```
